-- Drop tables if they exist to ensure clean slate (Fixes schema mismatch)
drop table if exists public.products cascade;
drop table if exists public.orders cascade;

-- Create Products Table
create table public.products (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  price numeric not null,
  image text not null,
  category text not null,
  description text
);

-- Create Orders Table
create table public.orders (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  username text not null,
  ucp_name text not null,
  items jsonb not null,
  total numeric not null,
  status text default 'Hazırlanıyor'::text,
  payment_method text,
  sender_character text,
  full_name text,
  address text,
  phone text
);

-- Enable Row Level Security (RLS)
alter table public.products enable row level security;
alter table public.orders enable row level security;

-- Create Policies (Simplified for prototype)
-- Allow read access to products for everyone
create policy "Public Products Read" on public.products for select using (true);

-- Allow insert access to orders for everyone (checkout)
create policy "Public Orders Insert" on public.orders for insert with check (true);

-- Allow read access to orders for everyone (for tracking) - In real app, restrict to owner
create policy "Public Orders Read" on public.orders for select using (true);

-- Allow all access for service role/admin (if using service key, but here we use anon for demo)
-- Ideally, you'd restrict write/update on products to admin users
create policy "Admin Products All" on public.products for all using (true); -- For demo simplicity
create policy "Admin Orders All" on public.orders for all using (true); -- For demo simplicity

-- Site Config (nav, banners)
create table if not exists public.site_config (
  key text primary key,
  value jsonb not null,
  updated_at timestamp with time zone default timezone('utc'::text, now())
);
alter table public.site_config enable row level security;
create policy "Public Site Config Read" on public.site_config for select using (true);
create policy "Admin Site Config All" on public.site_config for all using (true);
insert into public.site_config (key, value) values
  ('nav_items', '[{"label": "TÜM ÜRÜNLER", "href": "/"}, {"label": "GİYİM", "href": "/?category=Giyim"}, {"label": "AKSESUAR", "href": "/?category=Aksesuar"}]'::jsonb),
  ('hero_banners', '[{"image": "https://images.unsplash.com/photo-1576871337622-98d48d1cf531?q=80&w=1000&auto=format&fit=crop", "title": "YENİ SEZON", "buttonText": "ALIŞVERİŞE BAŞLA", "buttonLink": "/"}, {"image": "https://images.unsplash.com/photo-1552346154-21d32810aba3?q=80&w=1000&auto=format&fit=crop", "title": "AKSESUARLAR", "buttonText": "GÖZ AT", "buttonLink": "/?category=Aksesuar"}]'::jsonb)
on conflict (key) do nothing;

-- Insert Mock Data
insert into public.products (name, price, image, category, description)
values
  ('V.P. Signature Hoodie', 1200, 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?q=80&w=1000&auto=format&fit=crop', 'Giyim', 'Valley Park imza koleksiyonundan özel tasarım hoodie. %100 pamuklu kumaş.'),
  ('Urban Street Sneaker', 1850, 'https://images.unsplash.com/photo-1552346154-21d32810aba3?q=80&w=1000&auto=format&fit=crop', 'Ayakkabı', 'Sokak modasına uygun, rahat ve şık sneaker.'),
  ('Vintage Denim Jacket', 2100, 'https://images.unsplash.com/photo-1576871337622-98d48d1cf531?q=80&w=1000&auto=format&fit=crop', 'Dış Giyim', 'Klasik kesim vintage denim ceket.'),
  ('Minimalist Cap', 450, 'https://images.unsplash.com/photo-1588850561407-ed78c282e89b?q=80&w=1000&auto=format&fit=crop', 'Aksesuar', 'Her kombine uyan minimalist şapka.');
